'''
Global Symbol Table
===================

Each Python source file creates a symbol table at run-time.  Global variables (including global function objects)
are stored in a dictionary.  You can use the built-in, globals() to obtain this dictionary.  Some of the symbols
are generated by the Python interpreter itself; these will be dunder symbols (__xxxx__).  The rest of the symbols
will be ours. 
'''

def function1():pass
def function2():pass
x = 200
y = 300


def printGlobalSymbols():
    symbols = globals()
    print(type(globals()))
    for key, value in symbols.items():
        print(f"{key:20} {value}")
    
printGlobalSymbols()




