#! /bin/bash

# It is recommended to use:
#       pipenv install cothread
#
# to install these libraries, but I'm just using pip in this script

set -v
python -m pip install --index-url https://pypiserver.diamond.ac.uk  --user cothread
python -m pip install --index-url https://pypiserver.diamond.ac.uk  --user aapy
python -m pip install --index-url https://pypiserver.diamond.ac.uk  --user aioca
