
print(dir(object))
print("__class__: ", object.__class__)
print("__delattr__", object.__delattr__) 
print("__doc__: ", object.__doc__)
print("__format__: ", object.__format__)
print("__getattribute__: ", object.__getattribute__)
print("__hash__: ", object.__hash__)
print("__init__: ", object.__init__)
print("__new__: ", object.__new__)
print("__reduce__: ", object.__reduce__)
print("__reduce_ex__: ", object.__reduce_ex__)
print("__repr__: ", object.__repr__)
print("__setattr__: ", object.__setattr__)
print("__sizeof__: ", object.__sizeof__)
print("__str__: ", object.__str__)
print("__subclasshook__: ", object.__subclasshook__)

