[build-system]
requires = ["setuptools>=74.1", "wheel", "Cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
ext-modules = [
  {name = "cythonRoots", sources = ["cythonRoots.pyx"]} 
]
[project]
name = "cythonRoots"
version = "1.0.0"
requires-python = ">=3.8"
