print(("inf - 5000.0 =",  float('infinity') - 5000.0))
print(("inf - inf =", float('infinity') - float('infinity')))
print(("inf + inf =", float('infinity') + float('infinity')))
print(("inf / inf =", float('infinity') / float('infinity')))
print(("inf * inf =", float('infinity') * float('infinity')))
print(("inf * 0.0 =", float('infinity') * 0.0))
print(("nan + 5.0 =", float('NaN') + 5.0))
