# Generated by Django 5.1.3 on 2024-11-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeTeam', models.CharField(max_length=20)),
                ('homeScore', models.IntegerField(default=0)),
                ('awayTeam', models.CharField(max_length=20)),
                ('awayScore', models.IntegerField(default=0)),
            ],
        ),
    ]
