# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _myexample
else:
    import _myexample

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _myexample.delete_SwigPyIterator

    def value(self):
        return _myexample.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _myexample.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _myexample.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _myexample.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _myexample.SwigPyIterator_equal(self, x)

    def copy(self):
        return _myexample.SwigPyIterator_copy(self)

    def next(self):
        return _myexample.SwigPyIterator_next(self)

    def __next__(self):
        return _myexample.SwigPyIterator___next__(self)

    def previous(self):
        return _myexample.SwigPyIterator_previous(self)

    def advance(self, n):
        return _myexample.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _myexample.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _myexample.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _myexample.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _myexample.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _myexample.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _myexample.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _myexample:
_myexample.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _myexample.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _myexample.IntVector___nonzero__(self)

    def __bool__(self):
        return _myexample.IntVector___bool__(self)

    def __len__(self):
        return _myexample.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _myexample.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _myexample.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _myexample.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _myexample.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _myexample.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _myexample.IntVector___setitem__(self, *args)

    def pop(self):
        return _myexample.IntVector_pop(self)

    def append(self, x):
        return _myexample.IntVector_append(self, x)

    def empty(self):
        return _myexample.IntVector_empty(self)

    def size(self):
        return _myexample.IntVector_size(self)

    def swap(self, v):
        return _myexample.IntVector_swap(self, v)

    def begin(self):
        return _myexample.IntVector_begin(self)

    def end(self):
        return _myexample.IntVector_end(self)

    def rbegin(self):
        return _myexample.IntVector_rbegin(self)

    def rend(self):
        return _myexample.IntVector_rend(self)

    def clear(self):
        return _myexample.IntVector_clear(self)

    def get_allocator(self):
        return _myexample.IntVector_get_allocator(self)

    def pop_back(self):
        return _myexample.IntVector_pop_back(self)

    def erase(self, *args):
        return _myexample.IntVector_erase(self, *args)

    def __init__(self, *args):
        _myexample.IntVector_swiginit(self, _myexample.new_IntVector(*args))

    def push_back(self, x):
        return _myexample.IntVector_push_back(self, x)

    def front(self):
        return _myexample.IntVector_front(self)

    def back(self):
        return _myexample.IntVector_back(self)

    def assign(self, n, x):
        return _myexample.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _myexample.IntVector_resize(self, *args)

    def insert(self, *args):
        return _myexample.IntVector_insert(self, *args)

    def reserve(self, n):
        return _myexample.IntVector_reserve(self, n)

    def capacity(self):
        return _myexample.IntVector_capacity(self)
    __swig_destroy__ = _myexample.delete_IntVector

# Register IntVector in _myexample:
_myexample.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _myexample.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _myexample.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _myexample.DoubleVector___bool__(self)

    def __len__(self):
        return _myexample.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _myexample.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _myexample.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _myexample.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _myexample.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _myexample.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _myexample.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _myexample.DoubleVector_pop(self)

    def append(self, x):
        return _myexample.DoubleVector_append(self, x)

    def empty(self):
        return _myexample.DoubleVector_empty(self)

    def size(self):
        return _myexample.DoubleVector_size(self)

    def swap(self, v):
        return _myexample.DoubleVector_swap(self, v)

    def begin(self):
        return _myexample.DoubleVector_begin(self)

    def end(self):
        return _myexample.DoubleVector_end(self)

    def rbegin(self):
        return _myexample.DoubleVector_rbegin(self)

    def rend(self):
        return _myexample.DoubleVector_rend(self)

    def clear(self):
        return _myexample.DoubleVector_clear(self)

    def get_allocator(self):
        return _myexample.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _myexample.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _myexample.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _myexample.DoubleVector_swiginit(self, _myexample.new_DoubleVector(*args))

    def push_back(self, x):
        return _myexample.DoubleVector_push_back(self, x)

    def front(self):
        return _myexample.DoubleVector_front(self)

    def back(self):
        return _myexample.DoubleVector_back(self)

    def assign(self, n, x):
        return _myexample.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _myexample.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _myexample.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _myexample.DoubleVector_reserve(self, n)

    def capacity(self):
        return _myexample.DoubleVector_capacity(self)
    __swig_destroy__ = _myexample.delete_DoubleVector

# Register DoubleVector in _myexample:
_myexample.DoubleVector_swigregister(DoubleVector)


def say_hello(name):
    return _myexample.say_hello(name)

def say_goodbye(name):
    return _myexample.say_goodbye(name)

def average(v):
    return _myexample.average(v)

def average2(v):
    return _myexample.average2(v)


